<?php
/**
 * Verifone e-commerce Epayment module for Magento
 *
 * Feel free to contact Verifone e-commerce at support@paybox.com for any
 * question.
 *
 * LICENSE: This source file is subject to the version 3.0 of the Open
 * Software License (OSL-3.0) that is available through the world-wide-web
 * at the following URI: http://opensource.org/licenses/OSL-3.0. If
 * you did not receive a copy of the OSL-3.0 license and are unable
 * to obtain it through the web, please send a note to
 * support@paybox.com so we can mail you a copy immediately.
 *
 *
 * @version   3.0.4
 * @author    BM Services <contact@bm-services.com>
 * @copyright 2012-2017 Verifone e-commerce
 * @license   http://opensource.org/licenses/OSL-3.0
 * @link      http://www.paybox.com/
 */

$values = $this->getFormFields();
$helper = $this->helper('core');
try {
	if ($values['PBX_TYPEPAIEMENT'] == 'KWIXO') {
    	$url = $helper->escapeUrl($this->getKwixoUrl());
    }
    else if ($values['PBX_TYPEPAIEMENT'] == 'LIMONETIK') {
    	$url = $helper->escapeUrl($this->getAncvUrl());
    }
    else if (Mage::helper('pbxep/mobile')->isMobile()) {
    	$url = $helper->escapeUrl($this->getMobileUrl());
    }
    else {
    	if($values['PBX_SOURCE'] == 'RWD'){
    		$url = $this->escapeUrl($this->getResponsiveUrl());
    	}else{
    		$url = $this->escapeUrl($this->getSystemUrl());
    	}
    }
   	$type = $helper->escapeUrl($this->getInputType());
}
catch (Exception $e) {
    $error = $e;
}

if (isset($error)) {
?>
<p><center><?php echo $error->getMessage(); ?></center></p>
<?php
}
else {
?>
<form id="pbxep_form" method="post" action="<?php echo $url; ?>" enctype="application/x-www-form-urlencoded">
	<?php if (false): ?>
	<p>
		<?php echo $this->__('This is a debug view. Click continue to be redirected to Verifone e-commerce payment page.'); ?>
	</p>
	<?php else: ?>
	<p>
		<?php echo $this->__('You will be redirected to the Verifone e-commerce payment page. If not, please use the button bellow.'); ?>
	</p>
	<?php endif; ?>
	<center><button><?php echo $this->__('Continue...'); ?></button></center>
	<?php
	foreach ($values as $name => $value):
		$name = $helper->escapeHtml($name);
		$value = $helper->escapeHtml($value);
		if ($type != 'hidden'):
	?>
	<p><label for="<?php echo $name; ?>"><?php echo $name; ?></label>
	<?php endif; ?>
	<input type="<?php echo $type; ?>" id="<?php echo $name; ?>" name="<?php echo $name; ?>" value="<?php echo $value; ?>" />
	<?php if ($type != 'hidden'): ?>
	</p>
	<?php endif; ?>
	<?php endforeach; ?>
</form>
<?php if ($type == 'hidden'): ?>
<script type="text/javascript">
	window.setTimeout(function() {
		document.getElementById('pbxep_form').submit();
	}, 1);
</script>
<?php endif;
}
